# Generated by Django 5.1.3 on 2025-05-26 10:17

from django.db import migrations

def create_spisanie_and_subcategories(apps, schema_editor):
    Category = apps.get_model('traffic_controller', 'Category')
    Subcategory = apps.get_model('traffic_controller', 'Subcategory')

    # Создаем категорию "Списание"
    spisanie_category, created = Category.objects.get_or_create(
        name='Списание',
        defaults={
            'type': None  # Укажите тип, если есть. Если тип обязательный, нужно создать его заранее.
        }
    )

    # Создаем подкатегории "Farpost" и "Avito" связанные с "Списание"
    Subcategory.objects.get_or_create(
        name='Farpost',
        category=spisanie_category
    )
    Subcategory.objects.get_or_create(
        name='Avito',
        category=spisanie_category
    )

class Migration(migrations.Migration):

    dependencies = [
        ('traffic_controller', '0001_initial'),
        # добавьте сюда актуальные зависимости, если есть
    ]

    operations = [
        migrations.RunPython(create_spisanie_and_subcategories),
    ]